tasks:
  - name: "Business Review"
    description: "Analyze and review key business requirements and objectives given in the RFP input documents. This would be used as a guidance to create the bid strategy.
                  Use the read_proposal_inputs_tool tool to access the RFP inputs with the given proposal ID {proposal_id} as a parameter.
                  You will then summarize the inputs for the proposal team under the following sections 
                      1. Business Goals & Pain Points
                      2. Scope of Work
                      3. Regulatory & Compliance Needs
                      4. Budgetary Constraints & ROI Expectations
                  DO NOT add any new information ONLY summarize given inputs and total output should be less than 1000 words
                  Please think before you give your final answer."
    summary: "Analyze and review key business requirements and objectives."
    expected_output: "RFP Review document with summaries for Business Goals & Pain Points, Scope of Work, Regulatory & Compliance Needs, Budgetary Constraints & ROI Expectations"
    agent: "Business Analyst"
        
  - name: "Bid Strategy"
    description: "Define the Response Strategy.
                      Use the read_proposal_inputs_tool tool to access the RFP inputs with the given proposal ID {proposal_id} as a parameter.
                      Use the website scraping tool to scrape the bankofindia.co.in website to  learn about the client and their business.
                      Use the website scraping tool to scrape the tcs.com to learn about applicant company and their business.                     
                      Use the following guidelines to create a bid strategy:
                      1. Understand RFP Objectives: Use the Business Review task output to identify the key objectives and requirements of the RFP.
                      2. Client Relationship: Existing engagement or potential for long-term partnership
                      3. Opportunity Fit: Alignment with service offerings & domain expertise. Give a Go/No-Go decision.
                      4. Capability & Capacity: Readiness to deliver on the scope, timelines, and resource availability          
                      5. Competitive Landscape: Presence of major global competitors (Accenture, Capgemini, etc.)
                      6. Risk Assessment: Identify potential risks and mitigation strategies
                      7. Revenue & Profitability: Evaluating deal size, margins, and contract terms
                      8. Value Proposition: Highlight unique selling points and differentiators
                      DO NOT add any new information ONLY summarize given inputs and total output should be at least 200 but not more than 250 words
                    Please think before you give your final answer."
    summary: "Define the Response Strategy."
    expected_output: "Bid Strategy document with the following sections:
                      1. Executive Summary
                      2. Client Relationship
                      3. Opportunity Fit
                      4. Capability & Capacity
                      5. Competitive Analysis
                      6. SWOT analysis
                      7. Win Themes
                      8. Risk Mitigations
                      9. Resource considerations
                      10. High Level Solution Approach
                      11. Value Proposition
                      12. Pricing Strategy & Profitability
    agent: "Account Manager"
    context: ["Business Review"]


  - name: "Proposal Kickoff"
    description: "Based on the RFP Review and Bid Strategy plan task output prepare the proposal response and assign tasks for completion.
                      Use the read_proposal_inputs_tool tool to access the RFP inputs with the given proposal ID {proposal_id} as a parameter.
                      Use these guidelines to create a Proposal response template:
                      1. Proposal Team Roles & Responsibilities
                      2. Proposal Timeline & Milestones
                      3. Proposal Management Tools & Resources
                      4. Communication Plan
                      5. Risk Management Plan
                      6. Review Process & Quality Assurance
                      7. Final Submission Guidelines
                      Based on the template you need to assign tasks to the proposal team members to complete the document.
                      You have the following team
                      1. Solution Architect: Responsible for the solution design
                      2. Project Manager: Responsible for the execution/implementation plan
                      3. Financial Analyst: Responsible for the financial analysis
                      4. Legal Analyst: Responsible for the legal review
                      5. Proposal Writer: Responsible for the proposal draft
                      6. Proposal Owner: Responsible for the solution, execution plan, draft proposal review and finalization
                      The team member should be able to see the tasks assigned to them in the proposal management tool.
                      DO NOT add any new information ONLY summarize given inputs and total output should be at least 200 but not more than 250 words"
    expected_output: "A detailed, section-by-section Proposal Outline document mapping to RFP requirements, AND a separate list of high-level Task Assignments for each proposal team role."
    agent: "Proposal Owner"
    context: ["Business Review", "Bid Strategy"]



  - name: "Solution Design"
    description: "Create the solution design based on the business review."
    expected_output: "1. Solution Overview: Business value and functional scope. Core Functional Capabilities, \
                      2. Business/Application architecture: Logical and system interactions \
                      3. Technical architecture: Handling workflows and integrations, \
                      4. process/data flow: Handling workflows and integrations, \
                      5. Component wise breakdown: Modular, scalable, and maintainable architecture"
    agent: "Solution Architect"
    context: ["Proposal Kickoff"]

  - name: "Implementation Plan"
    description: "Details the execution strategy for the solution design."
    expected_output: "1. Project Plan: Scope, Phases, timelines and deliverables, 
                      2. Execution Methodology
                      3. Project Governance and Reporting
                      4. Assumptions and Exclusions 
                      5. Roles and REsponsibilities"
    agent: "Project Manager"
    context: ["Proposal Kickoff","Solution Design"]

  - name: "Approach"
    description: "Review the output of the Solution Design and Implementation Plan tasks, consolidate and finalize a proposal to submitted in response to the RFP.
                   The document should be complete in all respects except for financial and legal aspects.
                      Use the read_proposal_inputs_tool tool to access the RFP inputs with the given proposal ID {proposal_id} as a parameter."
    expected_output: "Draft proposal document post any review changes"
    agent: "Proposal Owner"
    context: ["Bid Strategy","Proposal Kickoff","Solution Design","Implementation Plan"]



  - name: "Financial Analysis"
    description: "Generate a financial breakdown from the solution document.
                    Use these guidelines to review the solution document:
                      1. Cost Estimation
                      2. Pricing Model
                      3. Revenue & Profitability Analysis
                      4. Risk Management & Compliance
                      5. Payment Terms
                      Use the read_proposal_inputs_tool tool to access the original RFP inputs with the given proposal ID {proposal_id} as a parameter."
    expected_output: "Financial Proposal Inputs in markdown format "
    agent: "Financial Analyst"
    context: ["Bid Strategy","Approach"]


  - name: "Legal Review"
    description: "Legal Review of the proposed solution and plan. All legal aspect required by the RFP should be covered.
                    Use these guidelines to review the solution document:
                      1. Contractual Obligations: Review the contract terms and conditions, including payment terms, deliverables, and timelines.
                      2. Legal compliance checklist
                      3. Risk management and mitigation strategies
                      4. Data privacy and security measures
                      5. Intellectual property rights and ownership
                  Use the read_proposal_inputs_tool tool to access the original RFP inputs with the given proposal ID {proposal_id} as a parameter."
    expected_output: "Legal Proposal Inputs in markdown format "
    agent: "Legal Analyst"
    context: ["Bid Strategy","Approach"]


  - name: "Draft Proposal"
    description: "Proposal Packaging & Finalization  of the proposal solution and plan.
                    Use the solution document and the financial and legal inputs to create a final proposal document.
                    Use these guidelines to review the document:
                      1. Executive Summary: A concise overview of the proposal, highlighting key points and benefits.
                      2. Detailed Solution Description: A comprehensive explanation of the proposed solution, including technical details and methodologies.
                      3. Financial Proposal: A clear breakdown of costs, pricing models, and payment terms.
                      4. Legal Terms and Conditions: A summary of the legal aspects, including contractual obligations and compliance measures.
                      5. Appendices: Any additional information, such as case studies, references, or supporting documents.
                      Formatting and Presentation: Ensure the document is well-organized, visually appealing, and easy to navigate.
                      This should be a complete document which covers all aspects of the proposal.
                      Use the read_proposal_inputs_tool tool to access the original RFP inputs with the given proposal ID {proposal_id} as a parameter."
    expected_output: "Fully formatted proposal document."
    agent: "Proposal Writer"
    context: ["Bid Strategy","Approach","Legal Review","Financial Analysis"]

  - name: "Final Review"
    description: "Final proposal document ready for submission post any review changes
                  Use the read_proposal_inputs_tool tool to access the original RFP inputs with the given proposal ID {proposal_id} as a parameter if needed."
    expected_output: "Final Proposal to be submitted"
    agent: "Proposal Owner"
    context: ["Draft Proposal"]

